name: update-doc

on: [push]

# This job installs dependencies, generates the documentation, and pushes it to `gh-pages`
jobs:
  deploy-documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install Poetry
      uses: snok/install-poetry@v1.3.3
      with:
          virtualenvs-create: true
          virtualenvs-in-project: true
    - name: Install dependencies
      run: |
        poetry --version
        poetry install -vv
        poetry run pip install --upgrade pip
        poetry run pip install sphinx sphinx-rtd-theme
        poetry run pip install sphinx-mdinclude
           
    - name: Generate documenation
      run: |
        cd docs
        poetry run make html
    
    # Push the HTML generated documentation to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
